DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS acronyms;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE acronym (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  acronym TEXT NOT NULL,
  description TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);